### ISSUE TITLE
External Editing Bug

### ISSUE THREAD

**Issue by ScriptInfra** [Sinacs/Joplin.Plugin.ReMoods.Theme#42] opened 2023-04-25 17:34 UTC
Please see the below screenshot. When selecting external editing, the 'Stop' appears to be covering the 'B':

Joplin v2.9.17
Remoods theme v4.2.1

![Screenshot_20230425_133031](https://user-images.githubusercontent.com/63025323/234356615-77e7a895-c7c0-4aaf-9db9-b4b4da2a082f.png)

**Comment by Sinacs** [comment] 2023-04-26 04:44
This issue has passed to Joplin due to it not being caused by ReMoods. I've already created the [issues](https://github.com/laurent22/joplin/issues/8084) on the Joplin repo, you can track how it's going any time.

I won't close this issue for now and will follow up after Joplin released a fix.

**Comment by Sinacs** [comment] 2023-05-23 05:16
Due to this issue has been a while without response from Joplin, I would like to give you a little tip to help you solve the problem, but it's not a perfect solution:

You can add the below code into your `userchrome.css`:

```css

/* Fix the buttons overlapping issue in rich text editor toolbar when toggling external editor */
.joplin-tinymce:not(#fake) .tox-toolbar__primary {
  padding-left: 120px !important;
}
```

After you save the files and restart Joplin, you will see the problem is gone:

![Screenshot 2023-05-23 125915](https://github.com/Sinacs/Joplin.Plugin.ReMoods.Theme/assets/110529913/6e6a4963-b961-4aab-9bd7-9efd44ad3a59)

But this solution will create another problem:

![image](https://github.com/Sinacs/Joplin.Plugin.ReMoods.Theme/assets/110529913/9fb2d8b5-a576-4cc7-bb1a-53b6403a6ef2)

You will see an unfixable gap between those buttons when you are not toggling external editor. And this is the reason I need to pass this issue to Joplin. Whatever, if you think it's helpful for you, just go for it! :)

**Comment by Sinacs** [comment] 2023-06-03 18:19
@FellipeMTX Yes, but it's only related to the Rich Text Editor. And ReMoods will not fix this issue before Joplin fixed it officially. Does this issue bother you?

**Comment by Sinacs** [comment] 2023-06-05 11:55
I've tried many ways to fix this issue but still haven't found a perfect solution. I'm now decided to close this issue, and label at won't fix.

**Comment by ScriptInfra** [comment] 2023-06-05 19:17
Thank you for looking into this! Hopefully it will be fixed in Joplin soon.

**Comment by Sinacs** [comment] 2023-06-05 20:20
Ok, it's welcome! It looks great, fix it only with CSS?

**Comment by Sinacs** [comment] 2023-07-09 23:54
I decided to close this issue, someone has added the commit to the Joplin repo, and you can keep following this issue by https://github.com/laurent22/joplin/issues/8084

**Closed by Sinacs** 2023-07-09 23:54 UTC
Labels: reviewing
